spring.application.name=song-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/song-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${APP_PORT:8082}
spring.cloud.inetutils.ignored-interfaces=lo
spring.cloud.inetutils.timeout-seconds=60
logging.level.org.springframework.cloud.commons.util=DEBUG
logging.level.org.springframework.cloud.commons.util.InetUtils=TRACE

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=5