server.port=${EUREKA_SERVICE_EXPOSE_PORT:8761}

spring.application.name=eureka-server

eureka.client.tls.enabled=false

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
spring.cloud.service-registry.auto-registration.enabled=false


eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

# === ACTUATOR ===
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.info.enabled=true
